

select:
  features:
    - X1_ActualPosition


transform:
  add-noise:
    frac: 0.10
    features:
      - X1_ActualPosition
    label: "X1_ActualPosition"



split:
  train_split: 0.6
scale:
  method: minmax

sequentialize:
  # History window size in milliseconds
  hist_size: 100
  # Use only every nth element
  use_elements: 1
  # Use mean power value over given window
  target_mean_window: 1


train:
  net: cnn
  n_epochs: 100
  batch_size: 128
  kernel_size: 4

evaluate:

