

select:
  features:
    - X1_ActualPosition
    - X1_CommandPosition

transform:
  add-noise:
    frac: 0.10
    features:
      - X1_ActualPosition
    label: "X1_ActualPosition"



split:
  train_split: 0.6
scale:

sequentialize:
  # History window size in deciseconds
  hist_size: 100
  # Use only every nth element
  use_elements: 1
  # Use mean power value over given window
  target_mean_window: 1


train:
  net: cnn
  n_epochs: 100
  batch_size: 500 #128
  kernel_size: 5 #4

evaluate:

